config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  resources :students do
    resources :comments
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def new

    end

    def create
        render plain: params[:article].inspect
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @student12 = Student.find(params[:student_id])
        @comment = @student12.comments.create(comment_params)
        redirect_to students_path(@student12)
    end

    private
    def comment_params
        params.require(:comment).permit(:commenter,:body)
    end
end

app/controllers/fighter_controller.rb
class FighterController < ApplicationController
    def new 
    end
    def create
        render plain: params[:fighter].inspect
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
def new
end

def index 
    @students = Student.all
end

def create
    # render plain: params[:student11].inspect
    @student12 = Student.new(student_params)
    @student12.save
    redirect_to @student12
end

def show
    @student12 = Student.find(params[:id])
end

def edit
    @student12 = Student.find(params[:id])
end

def update 
    @student12 = Student.find(params[:id])
    if @student12.update(student_params)
        redirect_to @student12
    else
        render 'edit'
    end
end

def destroy
    @student12 = Student.find(params[:id])
     @student12.destroy
        redirect_to students_path
    
end

private 
def student_params
    params.require(:student).permit(:title,:text)
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fighter_helper.rb
module FighterHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/fighter/new.html.erb
<h1>Create a New fighter</h1>


<%= form_for :fighters, url:fighter_path   do |x| %>
<p>
 <%= x.label :title %><br>
 <%= x.text_field :title%>
</p>
<p>
    <%= x.label :text %><br>
    <%= x.text_area :text%>
</p>
<p>
    <%= x.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogtry</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h1>Edit a New Student</h1>

<%= form_for @student12  do |x| %>
<p>
 <%= x.label :title %><br>
 <%= x.text_field :title%>
</p>
<p>
    <%= x.label :text %><br>
    <%= x.text_area :text%>
</p>
<p>
    <%= x.submit %>
    </p>
<% end %>

<p><%= link_to 'Blog', students_path %> | <%= link_to 'Home Page', root_path%></p>

app/views/students/index.html.erb
<h1>Listing all students</h1>
<p>
<%= link_to 'Create New Article',new_student_path  %>
</p>
<table>
<tr>
<th>Title</th>
<th>Text</th>
</tr>
<% @students.each do |x| %>
<tr>
<td><%= x.title %></td>
<td><%= truncate(x.text,length:75) %></td>
<td><%= link_to 'Show', student_path(x) %></td>
<td><%= link_to 'Edit', edit_student_path(x) %></td>
<td><%= link_to 'Delete',  student_path(x),
    method: :Delete,
    data: {confirm: 'Are you sure?'} 
    %>
</td>
</tr>
<% end %>
<p><%= link_to 'Home Page', root_path%></p>

</table>

app/views/students/new.html.erb
<h1>Create a New Student</h1>


<%= form_for :student115, url:students_path  do |x| %>
<p>
 <%= x.label :title %><br>
 <%= x.text_field :title%>
</p>
<p>
    <%= x.label :text %><br>
    <%= x.text_area :text%>
</p>
<p>
    <%= x.submit %>
    </p>
<% end %>

<p><%= link_to 'Blog', students_path %> | <%= link_to 'Home Page', root_path%></p>

app/views/students/show.html.erb
<p><strong>Title: </strong>
    <%= @student12.title %>
</p>

<p><strong>Text: </strong>
    <%= @student12.text %>
</p>

<hr>
<h2> Comments </h2>
<% @student12.comments.each do |c| %>
<p> <strong>Commentor</strong> <%= c.commenter%></p>
<p> <strong>Comment</strong> <%=c.body%></p><% end %>



<hr>
<h2> Add comment </h2>
<%= form_for([@student12,@student12.comments.build]) do |f| %>

<p>
<%= f.label :commenter %><br>
<%= f.text_field :commenter %>
</p>
<p>
<%= f.label :body %><br>
<%= f.text_area :body %>
</p>
<%= f.submit%>
 <%end%>

<p><%= link_to 'Blog', students_path %> | <%= link_to 'Home Page', root_path%></p>

app/views/welcome/inde.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/inde.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome To My Blog</h1>
<p><%= link_to 'Home', students_path %></p>
<p><%= link_to 'Blog',students_path %></p>